---
title: "homework-04-code"
format: docx
editor: visual
---

## Quarto

```{r Set-up}
library(tidyverse)
library(here)
library(performance)
library(broom)
library(flextable)
library(ggeffects)
library(car)
library(naniar)
library(lterdatasampler)
```

# Problem 1. "How does fish length _predict_ fish weight for trout perch (across all sample years)?"

1) 
Biological:
Null Hypothesis: Fish length does not predict fish weight for trout perch.

Alternative Hypothesis: Fish length does predict fish weight for trout perch. 

Mathematical:
Null hypothesis: β_1 = 0

Alternative hypothesis: β_1 ≠ 0

2) 

```{r read-data}
fish_data <- read_csv(here("data", "ntl6_v12.csv"))
```

```{r filter-data}
fish_data_filtered <- fish_data %>% 
  filter(spname == "TROUTPERCH")
```

```{r missing-data-vis}
gg_miss_var(fish_data_filtered) +
  labs (caption = str_wrap("There are 0 missing data on fish length, however there are 200 missing data on fish weight which does affect our hypothesis in how fish length predicts fish weight."))
```

```{r}
ggplot(data = fish_data_filtered, aes(x = length, y = weight)) + 
  geom_point()
```


3)
```{r}
modelobject <- lm(length ~ weight, data = fish_data_filtered) 
par(mfrow = c(2, 2))

plot(modelobject)

```


